name: check_udeps
description: checks for unused dependencies
runs:
  using: "composite"
  steps:
    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        target: wasm32-unknown-unknown

    - name: Install cargo-make
      shell: bash
      run: which cargo-make || cargo install cargo-make

    - name: Install cargo-udeps
      shell: bash
      run: which cargo-udeps || cargo install cargo-udeps

    - name: Check FE
      shell: bash
      run: |
        cd frontend
        cargo make udeps

    - name: Check BE
      shell: bash
      run: |
        cd backend
        cargo make udeps
