# https://github.com/ericseppanen/cargo-cranky
# cargo install cargo-cranky && cargo cranky

deny = [
    "warnings",
    "unused_imports",
    "unused_must_use",
    "unused_variables",
    "unused_mut",
    "dead_code",

    "clippy::all",
    "clippy::perf",
    "clippy::correctness",
    "clippy::complexity",
    "clippy::style",
    "clippy::nursery",
    "clippy::pedantic",
    # selected clippy::restriction (see https://rust-lang.github.io/rust-clippy/master/index.html#/?groups=restriction)
    # it is recommended to enable individually based on style and requirements
    "clippy::as_underscore",
    "clippy::assertions_on_result_states",
    "clippy::clone_on_ref_ptr",
    "clippy::create_dir",
    "clippy::dbg_macro",
    "clippy::decimal_literal_representation",
    "clippy::default_numeric_fallback",
    "clippy::empty_drop",
    "clippy::empty_structs_with_brackets",
    "clippy::exit",
    "clippy::filetype_is_file",
    "clippy::float_cmp_const",
    "clippy::fn_to_numeric_cast_any",
    "clippy::format_push_string",
    "clippy::get_unwrap",
    "clippy::integer_division",
    "clippy::lossy_float_literal",
    "clippy::mem_forget",
    "clippy::mixed_read_write_in_expression",
    "clippy::mutex_atomic",
    "clippy::needless_raw_strings",
    "clippy::non_ascii_literal",
    "clippy::panic",
    "clippy::print_stderr",
    "clippy::pub_without_shorthand",
    "clippy::rc_buffer",
    "clippy::rc_mutex",
    "clippy::redundant_type_annotations",
    "clippy::ref_patterns",
    "clippy::rest_pat_in_fully_bound_structs",
    "clippy::same_name_method",
    "clippy::string_add",
    "clippy::string_lit_chars_any",
    "clippy::string_slice",
    "clippy::string_to_string",
    "clippy::suspicious_xor_used_as_pow",
    "clippy::todo",
    "clippy::try_err",
    "clippy::unimplemented",
    "clippy::unnecessary_self_imports",
    "clippy::unneeded_field_pattern",
    "clippy::unseparated_literal_suffix",
    "clippy::if_then_some_else_none",
    "clippy::partial_pub_fields",
    "clippy::print_stdout",
    "clippy::unwrap_in_result",
    "clippy::unwrap_used",
    "clippy::use_debug",
    # which are these?
    "clippy::expect_used",
    "clippy::needless_update",
    "clippy::match_like_matches_macro",
    "clippy::from_over_into",
    "clippy::useless_conversion",
    "clippy::verbose_file_reads"
]

allow = [
    "clippy::module_name_repetitions"
]
