name: check_be
description: check and test backend
inputs:
  rust:
    description: "rust version"
    required: true
    default: "stable"
  os:
    description: "os type"
    required: true
    default: "ubuntu-latest"
runs:
  using: "composite"
  steps:
    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust }}
        components: clippy

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-make,nextest

    - name: Check BE
      shell: bash
      run: |
        cd backend
        cargo make checks_ci
