name: check_be
description: check and test backend
inputs:
  rust:
    description: 'rust version'
    required: true
    default: 'stable'
  os:
    description: 'os type'
    required: true
    default: 'ubuntu-latest'
runs:
  using: "composite"
  steps:
    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ input.os }}-${{ input.rust }}
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ input.rust }}
        components: clippy
    - name: Install cargo-make
      run: |
        which cargo-make || cargo install cargo-make
    - name: Check BE
      run: |
        cd backend
        cargo make checks_ci
    - name: Test BE
      run: |
        cd backend
        cargo t